name: web_usb_example
description: Example web app for web_usb package
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  web_usb:
    path: ../
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^3.0.0
