name: web_usb
description: A starting point for Dart libraries or applications.
version: 0.2.0
homepage: https://github.com/woodemi/web_usb.dart

environment:
  sdk: '>=3.9.2 <4.0.0'


dependencies:
  web: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
